(defvar my-packages '(
                      ack
                      ag
                      async
                      auto-complete
                      autopair
                      bind-key
                      bm
                      browse-kill-ring
                      cider
                      clojure-mode
                      closure-template-html-mode
                      company
                      company-web
                      csv-mode
                      cyberpunk-theme
                      cycle-resize
                      dash
                      diminish
                      dired-hacks-utils
                      dired-subtree
                      dirtree
                      discover
                      discover-js2-refactor
                      dtrt-indent
                      emmet-mode
                      epl
                      eproject
                      etags-select
                      flycheck
                      flymake-easy
                      flymake-json
                      flymake-less
                      fringe-helper
                      git-commit
                      git-gutter
                      git-gutter-fringe
                      git-timemachine
                      helm
                      helm-core
                      highlight-symbol
                      htmlize
                      ibuffer-vc
                      impatient-mode
                      js2-closure
                      js2-mode
                      js2-refactor
                      js-comint
                      js-doc
                      json-mode
                      json-reformat
                      json-snatcher
                      jump-char
                      kite
                      less-css-mode
                      let-alist
                      loccur
                      log4j-mode
                      magit
                      magit-filenotify
                      magit-popup
                      makey
                      multiple-cursors
                      neotree
                      nodejs-repl
                      page-break-lines
                      paredit
                      pkg-info
                      popup
                      python-mode
                      queue
                      rainbow-mode
                      rebox2
                      restclient
                      s
                      session
                      simple-httpd
                      skewer-mode
                      smex
                      todotxt
                      tree-mode
                      use-package
                      vlf
                      w3m
                      web-beautify
                      web-completion-data
                      web-mode
                      websocket
                      whole-line-or-region
                      windata
                      with-editor
                      wrap-region
                      ws-butler
                      yafolding
                      yaml-mode
                      yasnippet
                      zygospore
                      ))
